// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAstSpkE8bXAHCdzdosPN4SzswUED8yX_k',
    appId: '1:807782298312:web:e452b75bf914c6a737abfd',
    messagingSenderId: '807782298312',
    projectId: 'todo-route-892d6',
    authDomain: 'todo-route-892d6.firebaseapp.com',
    storageBucket: 'todo-route-892d6.appspot.com',
    measurementId: 'G-1EM5B1EK7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi11ugQ-WKDhxQsN5yV1aHFPelrwTn1LU',
    appId: '1:807782298312:android:1358bf37ec4f90f137abfd',
    messagingSenderId: '807782298312',
    projectId: 'todo-route-892d6',
    storageBucket: 'todo-route-892d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf4sL_lVygesNAMSCDtR1-qXXUcTeRyhw',
    appId: '1:807782298312:ios:98f8bc0ebdb1054037abfd',
    messagingSenderId: '807782298312',
    projectId: 'todo-route-892d6',
    storageBucket: 'todo-route-892d6.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf4sL_lVygesNAMSCDtR1-qXXUcTeRyhw',
    appId: '1:807782298312:ios:98f8bc0ebdb1054037abfd',
    messagingSenderId: '807782298312',
    projectId: 'todo-route-892d6',
    storageBucket: 'todo-route-892d6.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAstSpkE8bXAHCdzdosPN4SzswUED8yX_k',
    appId: '1:807782298312:web:376c28305e44260437abfd',
    messagingSenderId: '807782298312',
    projectId: 'todo-route-892d6',
    authDomain: 'todo-route-892d6.firebaseapp.com',
    storageBucket: 'todo-route-892d6.appspot.com',
    measurementId: 'G-MV75MJDPBT',
  );
}
